apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- deployment.yaml
- service.yaml
- httproute.yaml
images:
- name: demo
  newName: acraksplatdev.azurecr.io/demo
  newTag: 6d44c88ef77f6db45b5143594fd4217358d98214
