apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: demo
    newName: mcr.microsoft.com/azuredocs/aks-helloworld
    newTag: v1
